document.writeln("<footer>");
document.writeln("            <div class=\'footer-content\' align=\'center\'>");
document.writeln("                <p>版权所有 &copy; 2024 楠树村信息网站. All rights reserved.</p>");
document.writeln("                <p>地址：四川省德阳市旌阳区天元街道楠树村村委会</p>");
document.writeln("                <p>电话：13568227789</p>");
document.writeln("                <nav>");
document.writeln("                    <ul>");
document.writeln("                        <a href=\'../联系我们.html\'>联系我们</a>");
document.writeln("                    </ul>");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("        </footer>");